#language: python
#python:
#  - 3.7
#  - 3.6
#  - 3.5
#os:
#  - linux
#  - osx
#  - windows
#
#install:
#  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
#  - pip3 install -r requirements.txt
#  - pip3 install pandas
#  - pip3 install absl-py
#script:
#  - python3 artifacts_toy.py || python artifacts_toy.py
#  - python3 hyper_parameters_example.py || python hyper_parameters_example.py
#  - python3 manual_reporting.py || python manual_reporting.py


language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.7.6 on Xenial Linux"
      python:
        - 3.7.6           # this works for Linux but is ignored on macOS or Windows
        - 3.6.7           # this works for Linux but is ignored on macOS or Windows
        - 3.5.7           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
        - python -m pip install --upgrade pip
        - export PYTHONPATH=${PWD}
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - pip3 install -r requirements.txt
  - pip3 install pandas
  - pip3 install absl-py

# 'python' points to Python 2.7 on macOS but points to Python 3.8 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script:
  - cd examples
  - python3 artifacts_toy.py || python artifacts_toy.py
  - python3 hyper_parameters_example.py || python hyper_parameters_example.py
  - python3 manual_reporting.py || python manual_reporting.py