version: 2.1
description: Trains ci workflow
jobs:
    flake8_lint:
        docker:
          - image: circleci/python:3.7.4
        working_directory: ~/repo
        steps:
            # Step 1 : checkout source code to working directory
            - checkout
            # Step 2: create virtual env and install dependencies
            - run:
                name: install dependencies
                command: |
                  python3 -m venv venv
                  . venv/bin/activate
                  pip install -r requirements.txt
            # Step 3: install flake8
            - run:
                name: install flake8
                command: |
                  . venv/bin/activate
                  pip install flake8
            # Step 4: Run example
            - run:
                name: run example for internal check
                command: |
                  . venv/bin/activate
                  pip install pandas
                  pip install absl-py
                  export PYTHONPATH=${PWD}
                  cd examples
                  python artifacts_toy.py |& tee -a logs.txt
                  python hyper_parameters_example.py |& tee -a logs.txt
                  python manual_reporting.py |& tee -a logs.txt
            # Step 5: Run codestyle
            - run:
                name: run flake8
                command: |
                  . venv/bin/activate
                  flake8 --exclude=venv* trains*

            - store_artifacts:
                path: examples/logs.txt

workflows:
  main:
    jobs:
      - flake8_lint
