name: Get project stats
on: [issue_comment]

jobs:
  get-stats:
    if: contains(github.event.comment.body, '/get-stats')
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - run: |
          pwd
          ls -la /home/runner/work/trains/trains/.github/actions/get_stats
      - name: Get stats
        uses: ./.github/actions/get_stats
        with:
          TRIGGER_PHRASE: "/get-stats"
        env:
          TRAINS_API_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          TRAINS_API_SECRET_KEY: ${{ secrets.SECRET_KEY }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v2